apiVersion: apps/v1
kind: Deployment
metadata:
  name: porttrack
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: porttrack
  template:
    metadata:
      labels:
        app: porttrack
    spec:
      containers:
        - name: porttrack
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
